### ISSUE TITLE
你好，问一下，这个安装需要依赖搜狗输入法吗？

### ISSUE THREAD

**Issue by iamflowerdog** [sxzxs/Real-time-translation-typing#1]
辛苦作者写一下安装教程？

**Comment by iamflowerdog** [comment]
我在win10试了一下，用自带的微软输入法不可以

**Comment by sxzxs** [comment]
我测试过win10和win11, 自带输入法是支持的
管理员执行： exe，后，alt + y 会在光标处 出现一个红色的竖线就表示可以运行

**Comment by kxqing** [comment]
这个是不是还需要安装依赖，这个依赖怎么安装

**Comment by sxzxs** [comment]
用这个可以安装： https://zhangyue667.lanzouh.com/DirectXRepairEnhanced
或者去微软官网：https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by finzaghi9** [comment]
win10下，微软输入法，只能英翻中，中文输入法状态下按下alt+y，输出的就变成英文了，不再显示中文

**Comment by sxzxs** [comment]
> win10下，微软输入法，只能英翻中，中文输入法状态下按下alt+y，输出的就变成英文了，不再显示中文

这个时候也没法切换输入法吗

**Comment by finzaghi9** [comment]
> > win10下，微软输入法，只能英翻中，中文输入法状态下按下alt+y，输出的就变成英文了，不再显示中文
> 
> 这个时候也没法切换输入法吗 刚才修复了一个漏掉字符消息的问题，可以重新下载试试
![动画](https://github.com/sxzxs/Real-time-translation-typing/assets/197476/3a70e3b8-ab79-4fff-ba11-aa7d574a1559)
现在是另一种现象了，我第一排正常输入"测试"两字，然后右键复制，第二排输入"快捷键"三个字,第三排按alt+y 然后无论输入汉字还是英文，按回车，都会出现刚才复制的内容(跟ctrl+c一个效果)
