### ISSUE TITLE
微信聊天中无法使用

### ISSUE THREAD

**Issue by namexiaolu** [sxzxs/Real-time-translation-typing#11]
https://github.com/sxzxs/Real-time-translation-typing/assets/16086608/8ac83717-087c-415c-af0f-1b4b3e69c749

微信中虽然翻译了但是按回车时候什么都不显示。
大佬帮忙看一下

**Comment by sxzxs** [comment]
视频播放不了

**Comment by sxzxs** [comment]
我自己测试正常啊

**Comment by namexiaolu** [comment]
上传了个压缩包试一下能打开么?
我在记事本和vscode都能正常使用，就是微信中不行

**Comment by sxzxs** [comment]
要不你加这个群反馈吧：720101589

**Comment by namexiaolu** [comment]
好的
