### ISSUE TITLE
运行不了软件，win10的。

### ISSUE THREAD

**Issue by bfqbpq567** [sxzxs/Real-time-translation-typing#29]
点击后显示Script file not found
E:\效率神器\微信边写边译v2.0.11VAutoHotkey64.ahk。
![图片](https://github.com/sxzxs/Real-time-translation-typing/assets/66172873/bd62ad44-6e64-4823-a31a-48d92e583388)

**Comment by sxzxs** [comment]
你打开错了

**Comment by bfqbpq567** [comment]
> 你打开错了

那是怎么操作的
![7616C748](https://github.com/sxzxs/Real-time-translation-typing/assets/66172873/794b7c59-b2d6-436c-9709-ccffcb42cdd7)

**Comment by sxzxs** [comment]
![image](https://github.com/sxzxs/Real-time-translation-typing/assets/26515268/17749441-dd67-4062-8b1c-61c2f837b144)
