### ISSUE TITLE
是否存在安全隐患？

### ISSUE THREAD

**Issue by shulanlankk** [sxzxs/Real-time-translation-typing#37]
你好，请问我下了这个工具，然后打开网页版后想使用一下，打开了记事本，输入的后按回车没有反应，几次没有结果后，我尝试按了一下空格，然后电脑就像不受控制的疯狂点开记事本，并且关了又开，这一时间电脑根不受控制，我只好赶紧关机，开了后还是有一小段时间不受控制，我想知道这是否会有安全隐患。

现在工具文件我已经删除了，但我还是很担心。

**Comment by sxzxs** [comment]
原因是：网络有问题，导致结果阻塞，然后模拟按键操作乱序
重启还有问题，不理解

开源代码，你可以看看代码

**Comment by shulanlankk** [comment]
> 原因是：网络有问题，操作结果导致阻塞，然后模拟按键乱序 重启还有问题，不明白
> 
> 好的，谢谢
