### ISSUE TITLE
百度自动翻译无效

### ISSUE THREAD

**Issue by 5starvip** [sxzxs/Real-time-translation-typing#5]
已经按照说明,在配置文件,设置百度翻译自动翻译为 1 ,但是每次输入完还要打空格才能翻译,

**Comment by sxzxs** [comment]
配置完，需要重启，
我建议百度不需要设置为1，测试下来，api速度很慢，而且消耗太多。
下一个版本增加搜狗网页翻译的劫持版本，很流畅很多
