### ISSUE TITLE
希望Alt + Tab切换窗口之后 Typing Layer能够消失

### ISSUE THREAD

**Issue by xiaoxinshiwo** [sxzxs/Real-time-translation-typing#7]
![image](https://github.com/sxzxs/Real-time-translation-typing/assets/24218496/42ad5a2a-2d52-427b-8e05-b878e5f9fd2e)
![image](https://github.com/sxzxs/Real-time-translation-typing/assets/24218496/ac05a844-787c-49d5-aed0-35a825bef686)

**Comment by sxzxs** [comment]
已添加task
另外建议用web调用版本

**Comment by sxzxs** [comment]
已提交
